# Continuous Integration with GitHub Actions
name: module3_task2
# Controls when the workflow will run
on:
  # Triggers the workflow on push or once per day at midnight
  push:
    paths:
      - 'main'
  schedule:
    - cron: "30 22 * * 0-6"
# Jobs has two steps, clone the repo and execute 'make help'
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent sequence of tasks that will be executed as par of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      # so your job can access it
      - name: Clone the repository
        uses: actions/checkout@v3
      # executing the script setup.sh
      - name: executing the script setup.sh
        run: |
          cd module3_task2/
          ./setup.sh
      # Lint the Markdown files with markdownlint
      - name: run markdownlint command
        run: make lint -C module3_task2/
      # executing the rules make build
      - name: build the aplication
        run: make build -C module3_task2/

      # implement a zip file with the content website
      - name: run the  package to create a file zip
        run: make package -C module3_task2/
